#!/usr/bin/env python3
"""
Build Man Pages
Generates src/utils/man-pages.js from markdown files in docs/man/
"""

from pathlib import Path
import json

def escape_for_js(content):
    """Escape content for JavaScript template literal"""
    # Escape backslashes first, then backticks and ${
    content = content.replace('\\', '\\\\')
    content = content.replace('`', '\\`')
    content = content.replace('${', '\\${')
    return content

def main():
    man_dir = Path('docs/man')
    output_file = Path('src/utils/man-pages.js')

    if not man_dir.exists():
        print(f"Error: {man_dir} directory not found")
        return 1

    # Read all .md files
    man_pages = {}
    for filepath in sorted(man_dir.rglob('*.*.md')):
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            man_pages[filepath.name] = content

    if not man_pages:
        print(f"Warning: No .md files found in {man_dir}")
        return 1

    # Generate JavaScript content
    js_lines = [
        "/**",
        " * Man Pages Content",
        " * Auto-generated by build-man-pages.py",
        " * DO NOT EDIT - Edit files in docs/man/ instead",
        " */",
        "",
        "export const manPages = {"
    ]

    # Add each man page
    for i, (filename, content) in enumerate(man_pages.items()):
        escaped_content = escape_for_js(content)
        comma = "," if i < len(man_pages) - 1 else ""
        js_lines.append(f"  '{filename}': `{escaped_content}`{comma}")
        js_lines.append("")

    js_lines.append("};")
    js_lines.append("")

    # Write output
    output_content = '\n'.join(js_lines)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(output_content)

    print(f"Generated {output_file}")
    print(f"  {len(man_pages)} man pages: {', '.join(sorted(man_pages.keys()))}")
    return 0

if __name__ == '__main__':
    exit(main())
